runtime: nodejs12
env: standard

service: api

includes:
  - ./config/env_variables.yaml

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

network:
  session_affinity: true
